# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restoring
  continueOnError: false
  inputs:
    command: restore
    projects: '*.sln'
    

- task: DotNetCoreCLI@2
  displayName: Testing
  continueOnError: false
  inputs:
    command: test
    projects: '**/*.Test/*.csproj'

- task: SonarQubePrepare@4
  inputs:
    scannerMode: 'MSBuild'
    projectKey: 'e2af3999048a9ad743ab0f1efed3030e4dee506b'
    projectName: 'Crawler Wave'

- task: SonarQubeAnalyze@4    
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
