# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restoring
  continueOnError: false
  inputs:
    command: restore
    projects: '*.sln'
    
- task: SonarCloudPrepare@1
  displayName: Configuring SonarCloud
  inputs:
    SonarCloud: 'SonarCluodConnection'
    organization: 'afborgesdev-github'
    scannerMode: 'MSBuild'
    projectKey: 'afborgesDev_CrawlerWave'
    projectName: 'Crawler Wave'

- task: SonarCloudAnalyze@1
  displayName: Runing SonarCloudAnalyze

- task: DotNetCoreCLI@2
  displayName: Testing
  continueOnError: false
  inputs:
    command: test
    projects: '**/*.Test/*.csproj'

- task: SonarCloudPublish@1
  displayName: Pushing SonarCloudAnalyze
  inputs:
    pollingTimeoutSec: '300'

#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
