trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  openCoverFileName: 'coverage.opencover.xml'
  coberturaFileName: 'coverage.cobertura.xml'

steps:
    
- task: SonarCloudPrepare@1
  displayName: Configuring SonarCloud
  inputs:
    SonarCloud: 'SonarCluodConnection'
    organization: 'afborgesdev-github'
    scannerMode: 'MSBuild'
    projectKey: 'afborgesDev_CrawlerWave'
    projectName: 'Crawler Wave'
    extraProperties: |
      sonar.exclusions=**/obj/**,**/*.dll
      sonar.branch.name=$(Build.SourceBranchName)
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/TestResults/Coverage/$(openCoverFileName)
      sonar.cs.vstest.reportsPaths=$(Build.SourcesDirectory)/TestResults/Report/*.trx
      sonar.cs.xunit.reportsPaths=$(Build.SourcesDirectory)/TestResults/Report/*.trx

- task: DotNetCoreCLI@2
  displayName: Building
  continueOnError: false
  inputs:
    command: 'build'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Runing tests'
  continueOnError: false
  inputs:
    command: test
    projects: '**/*.Test/*.csproj'
    arguments: '-c $(buildConfiguration) --no-restore --logger trx /p:Exclude=[xunit.*]* /p:CollectCoverage=true "/p:CoverletOutputFormat=\"cobertura,opencover\""'

- task: PublishCodeCoverageResults@1
  displayName: 'Publishing coverage results'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/*.Test/$(coberturaFileName)'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'src/CrawlerWave.Test/'
    Contents: '$(openCoverFileName)'
    TargetFolder: '$(Build.SourcesDirectory)/TestResults/Coverage/'
    OverWrite: true
  displayName: 'copying coverage results'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'src/CrawlerWave.Test/'
    Contents: '*.trx'
    TargetFolder: '$(Build.SourcesDirectory)/TestResults/Report/'
    OverWrite: true
  displayName: 'copying tests report'

- task: DotNetCoreCLI@2
  displayName: Packing
  continueOnError: false
  inputs:
    command: 'pack'
    packagesToPack: '**/*.Core/*.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: Publish nuget package
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'CrawlerWaveNugetConnection'
    verbosityPush: 'Normal'    

- task: SonarCloudAnalyze@1
  displayName: Runing SonarCloudAnalyze

- task: SonarCloudPublish@1
  displayName: Pushing SonarCloudAnalyze
  inputs:
    pollingTimeoutSec: '300'