trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
    
- task: SonarCloudPrepare@1
  displayName: Configuring SonarCloud
  inputs:
    SonarCloud: 'SonarCluodConnection'
    organization: 'afborgesdev-github'
    scannerMode: 'MSBuild'
    projectKey: 'afborgesDev_CrawlerWave'
    projectName: 'Crawler Wave'

- task: DotNetCoreCLI@2
  displayName: Building
  continueOnError: false
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: Testing
  continueOnError: false
  inputs:
    command: 'test'
    projects: '**/*.Test/*.csproj'
    arguments: '--no-restore -c Debug --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    testRunTitle: 'Testing'

- task: PublishCodeCoverageResults@1
  displayName: 'Publishing coverage results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'

- task: SonarCloudAnalyze@1
  displayName: Runing SonarCloudAnalyze

- task: SonarCloudPublish@1
  displayName: Pushing SonarCloudAnalyze
  inputs:
    pollingTimeoutSec: '300'