name: .NET

on:
  push:
    branches:
      - main 
      - feature/*
      - bugfix/*
  pull_request:
    branches: 
      - main 
      - feature/*
      - bugfix/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      MSBUILDSINGLELOADCONTEXT:1

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore CrawlerWave.sln
    - name: Build
      run: dotnet build CrawlerWave.sln --no-restore
    - name: Test
      run: dotnet test src/CrawlerWave.Test/CrawlerWave.Test.csproj --no-build --verbosity normal
